// <auto-generated />
using Dotnet5.CorrectContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dotnet5.CorrectContext.Migrations
{
    [DbContext(typeof(CorrectContext))]
    partial class CorrectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Dotnet5.CorrectContext.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ellen",
                            LastName = "Hunt"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Lisa",
                            LastName = "Lilly"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Brianna",
                            LastName = "Salter"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Aidan",
                            LastName = "Synnot"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Alice",
                            LastName = "Paten"
                        });
                });

            modelBuilder.Entity("Dotnet5.CorrectContext.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@main.com"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@main.com"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@main.com"
                        },
                        new
                        {
                            Id = 4,
                            Email = "user4@main.com"
                        },
                        new
                        {
                            Id = 5,
                            Email = "user5@main.com"
                        });
                });

            modelBuilder.Entity("Dotnet5.CorrectContext.Models.User", b =>
                {
                    b.HasOne("Dotnet5.CorrectContext.Models.Profile", "Profile")
                        .WithOne("User")
                        .HasForeignKey("Dotnet5.CorrectContext.Models.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Dotnet5.CorrectContext.Models.Profile", b =>
                {
                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
